class MyThreadDemo {
	public static void main(String[] args) throws Exception{
		Thread.sleep(1000);
		Thread.currentThread().sleep(1000);
		System.out.println(new Thread().currentThread());	
		System.out.println(new Thread());
	}
}


/*	generated by compiler.................
 		Thread.sleep(1000L);
        Thread.currentThread();
        Thread.sleep(1000L);
        System.out.println((new Thread()).currentThread());
        System.out.println(new Thread());

*/